name: build

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:

  build_linux_wheels:
    name: Build wheels for Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - platform: arm64
        image:
          - container: quay.io/pypa/manylinux_2_28_aarch64

    steps:

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.arch.platform }}

      - name: Build wheels
        run: |
          docker run \
            -v $(pwd):/${{ github.workspace }}  \
            --platform linux/${{ matrix.arch.platform }} \
            ${{ matrix.image.container }} \
            pwd && ls && ls /opt && ls /opt/python && \
            /opt/python/cp312-cp312/bin/python3.12 -m build && \
            (cd dist && auditwheel repair *.whl)

      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux_${{ matrix.arch.platform }}_wheels
          path: dist/wheelhouse
